= asciidoctor-ant Task
========================
:asciidoc-url: http://asciidoc.org
:asciidoctor-url: http://asciidoctor.org
:asciidoctorj-url: https://github.com/asciidoctor/asciidoctorj
:issues: https://github.com/binout/asciidoctor-ant/issues
:ant-url: http://ant.apache.org/
:ant-classloader-url: http://enitsys.sourceforge.net/ant-classloadertask/
:issue-url: https://github.com/asciidoctor/asciidoctorj/issues/107
:binout-repo: http://repository-binout.forge.cloudbees.com/release/org/asciidoctor/asciidoctor-ant/

image:https://buildhive.cloudbees.com/job/binout/job/asciidoctor-ant/badge/icon["Build Status", link="https://buildhive.cloudbees.com/job/binout/job/asciidoctor-ant/"]

The asciidoctor-ant is the unofficial means of using {asciidoctor-url}[Asciidoctor] to render all your {asciidoc-url}[AsciiDoc] documentation using {ant-url}[Apache Ant].

== Installation

=== Prerequesites

* Ant (minimun Ant 1.8.0)
* {ant-classloader-url}[ant-classloadertask], as a workaround of known {issue-url}[issue] of {asciidoctorj-url}[Asciidoctor java integration].

=== Download

You can download the uber jar of asciidoctor-ant in {binout-repo}[binout repository]. This jar contains the Ant task and its dependencies : JRuby and {asciidoctorj-url}[asciidoctorj].

=== Declaration

[source,xml]
----
...
    <target name="asciidoctor-def">
        <taskdef resource="net/jtools/classloadertask/antlib.xml" classpath="lib/ant-classloadertask.jar"/>          <1>
        <classloader loader="thread" classpath="lib/asciidoctor-ant.jar"/>                                           <1>
        <taskdef name="asciidoctor" classname="org.asciidoctor.ant.AsciidoctorAntTask"/>
    </target>
...
----

<1> "lib" is a directory containing ant-classloadertask and the uber jar asciidoctor-ant.jar

== Usage

[source,xml]
----
...
   <asciidoctor sourceDirectory="src/test/resources" outputDirectory="target"/>
...
----

=== Configuration options

There are several configuration options that the asciidoctor-ant Task uses. The options are similar to asciidoctor-maven-plugin :

sourceDirectory:: the source directory of Asciidoc files (mandatory)
sourceDocumentName:: an override to process a single source file; defaults to all files in `${sourceDirectory}`
outputDirectory:: the ouput directory (mandatory)
imagesDir:: defaults to `images`, which will be relative to the directory containing the source files
backend:: defaults to `docbook`
doctype:: defaults to `article`
eruby:: defaults to erb, the version used in jruby
headerFooter:: defaults to `true`
compact:: defaults to `false`
templateDir:: disabled by default, defaults to `null`
templateEngine:: disabled by defaultÈ
sourceHighlighter:: enables and sets the source highlighter (currently `coderay` or `highlightjs` are supported)
embedAssets:: Embedd the CSS file, etc into the output, defaults to `false`

==== Builtin attributes

There are various attributes Asciidoctor recognizes. Below is a list of them and what they do::

title:: An override for the title of the document.

[source,xml]
----
...
   <asciidoctor sourceDirectory="src/test/resources" outputDirectory="target">
        <attribute key="title" value="Asciidoc Ant"/>
   </asciidoctor>
...
----

Many other attributes are possible. Until a canonical list is created for asciidoctor, you may find http://asciidoc.org/userguide.html#X88[this list] to be helpful.

