= asciidoctor-ant Task
========================
:asciidoc-url: http://asciidoc.org
:asciidoctor-url: http://asciidoctor.org
:asciidoctorj-url: https://github.com/asciidoctor/asciidoctorj
:issues: https://github.com/asciidoctor/asciidoctor-ant/issues
:ant-url: http://ant.apache.org/
:asciidoctor-ant-maven-repo: http://repo1.maven.org/maven2/org/asciidoctor/asciidoctor-ant/

image:https://buildhive.cloudbees.com/job/Asciidoctor/job/asciidoctor-ant/badge/icon["Build Status", link="https://buildhive.cloudbees.com/job/Asciidoctor/job/asciidoctor-ant/"]

The asciidoctor-ant is the unofficial means of using {asciidoctor-url}[Asciidoctor] to render all your {asciidoc-url}[AsciiDoc] documentation using {ant-url}[Apache Ant].

== Installation

=== Prerequesites

* Ant (minimun Ant 1.8.0)

=== Download

You can download the uber jar of asciidoctor-ant in {asciidoctor-ant-maven-repo}[Maven Central]. This jar contains the Ant task and its dependencies : JRuby and {asciidoctorj-url}[asciidoctorj].

[source,xml]
.Using Ant
----
...
      <get src="http://repo1.maven.org/maven2/org/asciidoctor/asciidoctor-ant/${asciidoctor-version}/asciidoctor-ant-${asciidoctor-version}.jar"
           dest="lib/asciidoctor-ant.jar" usetimestamp="true"/>
...
----

=== Declaration

[source,xml]
----
...
    <target name="asciidoctor-def">
        <taskdef name="asciidoctor" classname="org.asciidoctor.ant.AsciidoctorAntTask" classpath="lib/asciidoctor-ant.jar"/> <1>
    </target>
...
----

<1> "lib" is a directory containing the uber jar asciidoctor-ant.jar

== Usage

[source,xml]
----
...
   <asciidoctor sourceDirectory="src/test/resources" outputDirectory="target"/>
...
----

=== Configuration options

There are several configuration options that the asciidoctor-ant Task uses. The options are similar to asciidoctor-maven-plugin :

sourceDirectory:: the source directory of Asciidoc files (mandatory)
sourceDocumentName:: an override to process a single source file; defaults to all files in `${sourceDirectory}`
outputDirectory:: the ouput directory (mandatory)
baseDir:: (not ant's basedir) enables to set the root path for resouces (e.g. included files), defaults to Ant project base directory
relativeBaseDir:: only used when baseDir is not set, enables to specify that each AsciiDoc file must search for its resources in the same folder (for example, included files). Internally, for each AsciiDoc source, sets `baseDir` to the same path as the source file. Defaults to `false`
imagesDir:: defaults to `images`, which will be relative to the directory containing the source files
backend:: defaults to `docbook`
doctype:: defaults to `article`
eruby:: defaults to erb, the version used in jruby
headerFooter:: defaults to `true`
compact:: defaults to `false`
templateDir:: disabled by default, defaults to `null`
templateEngine:: disabled by defaultÈ
sourceHighlighter:: enables and sets the source highlighter (currently `coderay` or `highlightjs` are supported)
embedAssets:: Embedd the CSS file, etc into the output, defaults to `false`

==== Builtin attributes

There are various attributes Asciidoctor recognizes. Below is a list of them and what they do :

title:: An override for the title of the document.

[source,xml]
----
...
   <asciidoctor sourceDirectory="src/test/resources" outputDirectory="target">
        <attribute key="title" value="Asciidoc Ant"/>
   </asciidoctor>
...
----

Many other attributes are possible. Until a canonical list is created for asciidoctor, you may find http://asciidoc.org/userguide.html#X88[this list] to be helpful.
